# Header
menu:
  首页: /
  归档: /archives
  相册: /gallery
  关于: /about
rss: /atom.xml

# Content
excerpt_link: 阅读全文...
fancybox: true

feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '

# Miscellaneous
favicon: /favicon.png


# Local search
# Dependencies: https://github.com/flashlab/hexo-generator-search
local_search:
  enable: true
  # if auto, trigger search by changing input
  # if manual, trigger search by pressing enter key or search button
  trigger: auto
  # show top n results per article, show all results by setting to -1
  top_n_per_article: 1
  unescape: true


#valine:
#  enable: false
#  appid:  h9Drto5YdVL1gwR6tYLYzwDu-gzGzoHsz
#  appkey: Gp6S7o0xPmfwqdXWe0DqOlfE